### ISSUE TITLE
Create link between event registration options and question options

### ISSUE THREAD

**Issue by MartinBenediktBusch** [lexicongovernance/forum-backend#84]
### Overview 

In certain scenarios, we find it beneficial to dynamically populate question options during event registration, drawing directly from specific fields such as the research proposal title and summary.

### Proposed Solution

Implementation of a dedicated service, similar to the existing `usersToGroup` service, that manages the transition of registration options to question options. Below is an example structure for such a service:

```typescript
import { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import * as db from '../db';
import { eq } from 'drizzle-orm';

export async function convertRegistrationToQuestion(
  dbPool: PostgresJsDatabase<typeof db>,
  registrationOption: string,
  flag: boolean,
): Promise<db.RegistrationToQuestion[] | null> {
  // Logic to convert registration option to question option based on the provided flag
  // ...

  // Return the newly converted question options
  return convertedQuestionOptions;
}
```

### Additional Features Implementation Should Have

1. **Strict Character Limit and Input Validations:**
Implement strict character limits and other input validations, including captions, on registration options such as research title and proposal description. This ensures data integrity and consistency in the information collected during event registration.

2. **Flagging for Enhanced Control:**
Introduce the ability to flag registration options, offering control over their transition into question options. For instance, organizers can set a flag to determine whether a registration option automatically becomes a question option. If the flag is set to false, the registration option will not transform into a question option, allowing for greater flexibility and customization based on the quality or relevance of the submitted research proposal. This feature enhances the platform's adaptability to diverse event requirements while maintaining the option to gate event registrations based on specific criteria.

**Comment by diegoalzate** [comment]
I like the convertRegistrationToQuestion service idea. I would like to say that we would want to be able to know who proposed a questionOption so this would probably require db changes that have not yet been stated in the issue.

Is the goal to have a pivot table between question option and registration option? Or is it to add a possible nullable id to reference a registration option in the question option?

Also this conversion should be controlled. Not all fields should be a questionOption so maybe a possible value that is added to the registration_field
